# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\software_project\可视化\integration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 720, 512))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.page1_frame = QtWidgets.QFrame(self.page_1)
        self.page1_frame.setGeometry(QtCore.QRect(0, 0, 720, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page1_frame.sizePolicy().hasHeightForWidth())
        self.page1_frame.setSizePolicy(sizePolicy)
        self.page1_frame.setStyleSheet("#page1_frame {\n"
"    background-image: url(:/icons/UI/1背景.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;\n"
"}\n"
"\n"
"")
        self.page1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page1_frame.setObjectName("page1_frame")
        self.label = QtWidgets.QLabel(self.page1_frame)
        self.label.setGeometry(QtCore.QRect(270, 160, 338, 79))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 48pt \"Impact\";\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.pushButton_close = QtWidgets.QPushButton(self.page1_frame)
        self.pushButton_close.setGeometry(QtCore.QRect(690, 10, 21, 21))
        self.pushButton_close.setStyleSheet("#pushButton_close{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}\n"
"#pushButton_close:hover{\n"
"     background-color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_close:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.pushButton_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/UI/叉.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon)
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_begin = QtWidgets.QPushButton(self.page1_frame)
        self.pushButton_begin.setGeometry(QtCore.QRect(350, 310, 161, 61))
        self.pushButton_begin.setStyleSheet("#pushButton_begin{\n"
"    border:none;\n"
"    background-color: rgb(180, 90, 85);\n"
"    border-radius:15px;\n"
"    font: 24pt \"联盟起艺卢帅正锐黑体\";\n"
"    background-image: url(:/icons/UI/红色矩形.png);\n"
"}\n"
"#pushButton_begin:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px\n"
"}\n"
"#pushButton_begin:hover{\n"
"    color:rgb(239, 239, 239)\n"
"}")
        self.pushButton_begin.setObjectName("pushButton_begin")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.page2_frame = QtWidgets.QFrame(self.page_2)
        self.page2_frame.setGeometry(QtCore.QRect(0, 0, 720, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page2_frame.sizePolicy().hasHeightForWidth())
        self.page2_frame.setSizePolicy(sizePolicy)
        self.page2_frame.setStyleSheet("#page2_frame{\n"
"    background-image: url(:/icons/UI/2背景.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;\n"
"}\n"
"\n"
"")
        self.page2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page2_frame.setObjectName("page2_frame")
        self.pushButton_close2 = QtWidgets.QPushButton(self.page2_frame)
        self.pushButton_close2.setGeometry(QtCore.QRect(690, 10, 21, 21))
        self.pushButton_close2.setStyleSheet("#pushButton_close2{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}\n"
"#pushButton_close2:hover{\n"
"     background-color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_close2:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.pushButton_close2.setText("")
        self.pushButton_close2.setIcon(icon)
        self.pushButton_close2.setObjectName("pushButton_close2")
        self.frame_page2_l = QtWidgets.QFrame(self.page2_frame)
        self.frame_page2_l.setGeometry(QtCore.QRect(140, 250, 131, 171))
        self.frame_page2_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page2_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page2_l.setObjectName("frame_page2_l")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_page2_l)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group1_namein = QtWidgets.QLineEdit(self.frame_page2_l)
        self.group1_namein.setStyleSheet("#group1_namein{\n"
"    background-color:rgb(239, 239, 239);\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.group1_namein.setText("")
        self.group1_namein.setObjectName("group1_namein")
        self.verticalLayout.addWidget(self.group1_namein)
        self.pushButton_l1 = QtWidgets.QPushButton(self.frame_page2_l)
        self.pushButton_l1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_l1.setStyleSheet("#pushButton_l1{\n"
"    border:none;\n"
"    background-color: rgb(21, 133, 114);\n"
"    border-radius:15px;\n"
"    font: 14pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_l1:hover{\n"
"    background-color:rgb(8, 69, 57)\n"
"}\n"
"#pushButton_l1:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px;\n"
"\n"
"}")
        self.pushButton_l1.setObjectName("pushButton_l1")
        self.verticalLayout.addWidget(self.pushButton_l1)
        self.pushButton_l2 = QtWidgets.QPushButton(self.frame_page2_l)
        self.pushButton_l2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_l2.setStyleSheet("#pushButton_l2{\n"
"    border:none;\n"
"    background-color: rgb(21, 133, 114);\n"
"    border-radius:15px;\n"
"    font: 14pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_l2:hover{\n"
"    background-color:rgb(8, 69, 57)\n"
"}\n"
"#pushButton_l2:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px\n"
"}")
        self.pushButton_l2.setObjectName("pushButton_l2")
        self.verticalLayout.addWidget(self.pushButton_l2)
        self.frame_page2_r = QtWidgets.QFrame(self.page2_frame)
        self.frame_page2_r.setGeometry(QtCore.QRect(440, 250, 131, 171))
        self.frame_page2_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page2_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page2_r.setObjectName("frame_page2_r")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_page2_r)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group2_namein = QtWidgets.QLineEdit(self.frame_page2_r)
        self.group2_namein.setStyleSheet("#group2_namein{\n"
"    background-color:rgb(239, 239, 239);\n"
"    color:rgb(0, 0, 0)\n"
"}")
        self.group2_namein.setText("")
        self.group2_namein.setObjectName("group2_namein")
        self.verticalLayout_2.addWidget(self.group2_namein)
        self.pushButton_r1 = QtWidgets.QPushButton(self.frame_page2_r)
        self.pushButton_r1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_r1.setStyleSheet("#pushButton_r1{\n"
"    border:none;\n"
"    background-color: rgb(21, 133, 114);\n"
"    border-radius:15px;\n"
"    font: 14pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_r1:hover{\n"
"    background-color:rgb(8, 69, 57)\n"
"}\n"
"#pushButton_r1:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px\n"
"}")
        self.pushButton_r1.setObjectName("pushButton_r1")
        self.verticalLayout_2.addWidget(self.pushButton_r1)
        self.pushButton_r2 = QtWidgets.QPushButton(self.frame_page2_r)
        self.pushButton_r2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_r2.setStyleSheet("#pushButton_r2{\n"
"    border:none;\n"
"    background-color: rgb(21, 133, 114);\n"
"    border-radius:15px;\n"
"    font: 14pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_r2:hover{\n"
"    background-color:rgb(8, 69, 57)\n"
"}\n"
"#pushButton_r2:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px\n"
"}")
        self.pushButton_r2.setObjectName("pushButton_r2")
        self.verticalLayout_2.addWidget(self.pushButton_r2)
        self.pushButton_vs = QtWidgets.QPushButton(self.page2_frame)
        self.pushButton_vs.setGeometry(QtCore.QRect(325, 330, 62, 60))
        self.pushButton_vs.setStyleSheet("#pushButton_vs{\n"
"    background-color:transparent;\n"
"    background-image:url(:/icons/UI/对战-未选中1.png);\n"
"    border:rgb(0, 0, 0)\n"
"}\n"
"#pushButton_vs:hover {  \n"
" background-image: url(:/icons/UI/对战-选中1.png);  \n"
"}\n"
"\n"
"#pushButton_vs:pressed{\n"
"    position: relative;  \n"
"    top: 10px;  \n"
"    left: 20px;  \n"
"}")
        self.pushButton_vs.setText("")
        self.pushButton_vs.setObjectName("pushButton_vs")
        self.frame_page2_tip = QtWidgets.QFrame(self.page2_frame)
        self.frame_page2_tip.setGeometry(QtCore.QRect(270, 405, 171, 31))
        self.frame_page2_tip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page2_tip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page2_tip.setObjectName("frame_page2_tip")
        self.stackedWidget_tip = QtWidgets.QStackedWidget(self.frame_page2_tip)
        self.stackedWidget_tip.setGeometry(QtCore.QRect(0, 0, 172, 32))
        self.stackedWidget_tip.setStyleSheet("#page2_in{\n"
"    background-color:transparent\n"
"}\n"
"#page2_numtip{\n"
"    background-color:transparent\n"
"}\n"
"#page2_filetip{\n"
"    background-color:transparent\n"
"}")
        self.stackedWidget_tip.setObjectName("stackedWidget_tip")
        self.page2_in = QtWidgets.QWidget()
        self.page2_in.setObjectName("page2_in")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page2_in)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_in = QtWidgets.QLabel(self.page2_in)
        self.label_in.setStyleSheet("color:rgb(180, 90, 85);\n"
"font: 8\n"
"pt \"联盟起艺卢帅正锐黑体\";")
        self.label_in.setObjectName("label_in")
        self.verticalLayout_4.addWidget(self.label_in)
        self.stackedWidget_tip.addWidget(self.page2_in)
        self.page2_filetip = QtWidgets.QWidget()
        self.page2_filetip.setObjectName("page2_filetip")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page2_filetip)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_filetip = QtWidgets.QLabel(self.page2_filetip)
        self.label_filetip.setStyleSheet("color:rgb(180, 90, 85);\n"
"font: 8\n"
"pt \"联盟起艺卢帅正锐黑体\";")
        self.label_filetip.setObjectName("label_filetip")
        self.horizontalLayout_2.addWidget(self.label_filetip)
        self.stackedWidget_tip.addWidget(self.page2_filetip)
        self.page2_numtip = QtWidgets.QWidget()
        self.page2_numtip.setObjectName("page2_numtip")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page2_numtip)
        self.verticalLayout_5.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_numtip = QtWidgets.QLabel(self.page2_numtip)
        self.label_numtip.setStyleSheet("color:rgb(180, 90, 85);\n"
"font: 9\n"
"pt \"联盟起艺卢帅正锐黑体\";")
        self.label_numtip.setObjectName("label_numtip")
        self.verticalLayout_5.addWidget(self.label_numtip)
        self.stackedWidget_tip.addWidget(self.page2_numtip)
        self.frame_page2_vsnum = QtWidgets.QFrame(self.page2_frame)
        self.frame_page2_vsnum.setGeometry(QtCore.QRect(290, 280, 131, 31))
        self.frame_page2_vsnum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page2_vsnum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page2_vsnum.setObjectName("frame_page2_vsnum")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_page2_vsnum)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_page2_vsnum)
        self.label_3.setStyleSheet("font: 9pt \"联盟起艺卢帅正锐黑体\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.frame_page2_vsnum)
        self.comboBox.setMouseTracking(False)
        self.comboBox.setStyleSheet("background-color:rgb(21, 133, 114);\n"
"font: 5pt \"联盟起艺卢帅正锐黑体\";\n"
"border-radius:7px;\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    spacing: 20px;\n"
"}")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.page3_frame = QtWidgets.QFrame(self.page_3)
        self.page3_frame.setGeometry(QtCore.QRect(0, 0, 720, 512))
        font = QtGui.QFont()
        font.setFamily("IPix")
        font.setPointSize(18)
        self.page3_frame.setFont(font)
        self.page3_frame.setStyleSheet("#page3_frame{\n"
"    background-image: url(:/icons/UI/3背景.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;\n"
"}\n"
"")
        self.page3_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page3_frame.setObjectName("page3_frame")
        self.pushButton_close3 = QtWidgets.QPushButton(self.page3_frame)
        self.pushButton_close3.setGeometry(QtCore.QRect(690, 10, 21, 21))
        self.pushButton_close3.setStyleSheet("#pushButton_close3{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}\n"
"#pushButton_close3:hover{\n"
"     background-color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_close3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.pushButton_close3.setText("")
        self.pushButton_close3.setIcon(icon)
        self.pushButton_close3.setObjectName("pushButton_close3")
        self.widget = QtWidgets.QWidget(self.page3_frame)
        self.widget.setGeometry(QtCore.QRect(40, 210, 621, 151))
        self.widget.setObjectName("widget")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(20, 18, 600, 51))
        self.progressBar.setMinimumSize(QtCore.QSize(600, 40))
        self.progressBar.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("IPix")
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("#progressBar{\n"
"    background-color:rgb(239, 239, 239);\n"
"    color:black;\n"
"    border-radius:15px;\n"
"\n"
"}\n"
"#progressBar:chunk{\n"
"    background-color:rgb(21, 133, 114);\n"
"    border-radius:15px\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(270, 90, 211, 41))
        self.label_2.setStyleSheet("\n"
"font: 24pt \"IPix\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(200, 80, 75, 51))
        self.pushButton.setStyleSheet("background-color:transparent;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\code\\software_project\\可视化\\UI/蜂蜜.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.page4_frame = QtWidgets.QFrame(self.page_4)
        self.page4_frame.setGeometry(QtCore.QRect(0, 0, 720, 512))
        self.page4_frame.setStyleSheet("#page4_frame{\n"
"    background-image: url(:/icons/UI/3背景.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: contain;\n"
"}\n"
"")
        self.page4_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.page4_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.page4_frame.setObjectName("page4_frame")
        self.pushButton_close4 = QtWidgets.QPushButton(self.page4_frame)
        self.pushButton_close4.setGeometry(QtCore.QRect(690, 10, 21, 21))
        self.pushButton_close4.setStyleSheet("#pushButton_close4{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}\n"
"#pushButton_close4:hover{\n"
"     background-color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_close4:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}")
        self.pushButton_close4.setText("")
        self.pushButton_close4.setIcon(icon)
        self.pushButton_close4.setObjectName("pushButton_close4")
        self.stackedWidget_page4 = QtWidgets.QStackedWidget(self.page4_frame)
        self.stackedWidget_page4.setGeometry(QtCore.QRect(0, 40, 720, 471))
        self.stackedWidget_page4.setMinimumSize(QtCore.QSize(720, 0))
        self.stackedWidget_page4.setMaximumSize(QtCore.QSize(720, 16777215))
        self.stackedWidget_page4.setStyleSheet("background-color:transparent")
        self.stackedWidget_page4.setObjectName("stackedWidget_page4")
        self.page_chart = QtWidgets.QWidget()
        self.page_chart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_chart.setObjectName("page_chart")
        self.frame_bee = QtWidgets.QFrame(self.page_chart)
        self.frame_bee.setGeometry(QtCore.QRect(130, 70, 460, 121))
        self.frame_bee.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bee.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bee.setObjectName("frame_bee")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_bee)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bee_l = QtWidgets.QPushButton(self.frame_bee)
        self.bee_l.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/UI/蜜蜂左.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bee_l.setIcon(icon2)
        self.bee_l.setIconSize(QtCore.QSize(100, 100))
        self.bee_l.setObjectName("bee_l")
        self.horizontalLayout_3.addWidget(self.bee_l)
        self.bee_r = QtWidgets.QPushButton(self.frame_bee)
        self.bee_r.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/UI/蜜蜂右.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bee_r.setIcon(icon3)
        self.bee_r.setIconSize(QtCore.QSize(100, 100))
        self.bee_r.setObjectName("bee_r")
        self.horizontalLayout_3.addWidget(self.bee_r)
        self.stackedWidget_win = QtWidgets.QStackedWidget(self.page_chart)
        self.stackedWidget_win.setGeometry(QtCore.QRect(0, 110, 720, 161))
        self.stackedWidget_win.setObjectName("stackedWidget_win")
        self.win = QtWidgets.QWidget()
        self.win.setObjectName("win")
        self.stackedWidget_win.addWidget(self.win)
        self.win1 = QtWidgets.QWidget()
        self.win1.setObjectName("win1")
        self.pushButton_win1 = QtWidgets.QPushButton(self.win1)
        self.pushButton_win1.setGeometry(QtCore.QRect(140, 20, 60, 50))
        self.pushButton_win1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/UI/像素_奖杯.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_win1.setIcon(icon4)
        self.pushButton_win1.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_win1.setObjectName("pushButton_win1")
        self.stackedWidget_win.addWidget(self.win1)
        self.win2 = QtWidgets.QWidget()
        self.win2.setObjectName("win2")
        self.pushButton_win2 = QtWidgets.QPushButton(self.win2)
        self.pushButton_win2.setGeometry(QtCore.QRect(520, 20, 60, 50))
        self.pushButton_win2.setText("")
        self.pushButton_win2.setIcon(icon4)
        self.pushButton_win2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_win2.setObjectName("pushButton_win2")
        self.stackedWidget_win.addWidget(self.win2)
        self.frame_name = QtWidgets.QFrame(self.page_chart)
        self.frame_name.setGeometry(QtCore.QRect(130, 200, 460, 37))
        self.frame_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_name.setObjectName("frame_name")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_name)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.group1_nameout = QtWidgets.QLabel(self.frame_name)
        self.group1_nameout.setStyleSheet("#group1_nameout{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"}\n"
"")
        self.group1_nameout.setObjectName("group1_nameout")
        self.horizontalLayout_4.addWidget(self.group1_nameout)
        self.group2_nameout = QtWidgets.QLabel(self.frame_name)
        self.group2_nameout.setStyleSheet("#group2_nameout{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"}\n"
"")
        self.group2_nameout.setObjectName("group2_nameout")
        self.horizontalLayout_4.addWidget(self.group2_nameout)
        self.pushButton_detail = QtWidgets.QPushButton(self.page_chart)
        self.pushButton_detail.setGeometry(QtCore.QRect(280, 380, 180, 41))
        self.pushButton_detail.setStyleSheet("#pushButton_detail{\n"
"    border:none;\n"
"    background-color: rgb(21, 133, 114);\n"
"    border-radius:15px;\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(239, 239, 239)\n"
"}\n"
"#pushButton_detail:hover{\n"
"    background-color:rgb(8, 69, 57)\n"
"}\n"
"#pushButton_detail:pressed{\n"
"    padding-top:6px;\n"
"    padding-left:6px;\n"
"\n"
"}")
        self.pushButton_detail.setObjectName("pushButton_detail")
        self.frame_l = QtWidgets.QFrame(self.page_chart)
        self.frame_l.setGeometry(QtCore.QRect(180, 260, 141, 101))
        self.frame_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_l.setObjectName("frame_l")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_l)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_l)
        self.label_4.setStyleSheet("#label_4{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"    background-color: rgb(239, 239, 239);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.frame_l)
        self.label_6.setStyleSheet("#label_6{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"    background-color: rgb(239, 239, 239);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.frame_r = QtWidgets.QFrame(self.page_chart)
        self.frame_r.setGeometry(QtCore.QRect(400, 260, 141, 101))
        self.frame_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_r.setObjectName("frame_r")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_r)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_r)
        self.label_5.setStyleSheet("#label_5{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"    background-color: rgb(239, 239, 239);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.frame_r)
        self.label_7.setStyleSheet("#label_7{\n"
"    font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    qproperty-alignment: \'AlignCenter|AlignVCenter\';\n"
"    background-color: rgb(239, 239, 239);\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.average = QtWidgets.QFrame(self.page_chart)
        self.average.setGeometry(QtCore.QRect(50, 260, 121, 101))
        self.average.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.average.setFrameShadow(QtWidgets.QFrame.Raised)
        self.average.setObjectName("average")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.average)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.average)
        self.label_8.setStyleSheet("font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(0, 0, 0)")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.average)
        self.label_9.setStyleSheet("font: 12pt \"联盟起艺卢帅正锐黑体\";\n"
"    color:rgb(0, 0, 0)")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.stackedWidget_page4.addWidget(self.page_chart)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_page4.addWidget(self.page_5)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_tip.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.stackedWidget_page4.setCurrentIndex(0)
        self.stackedWidget_win.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bee  Farming"))
        self.pushButton_begin.setText(_translate("MainWindow", "开始对战"))
        self.pushButton_l1.setText(_translate("MainWindow", "蜜 蜂"))
        self.pushButton_l2.setText(_translate("MainWindow", "黄 蜂"))
        self.pushButton_r1.setText(_translate("MainWindow", "蜜 蜂"))
        self.pushButton_r2.setText(_translate("MainWindow", "黄 蜂"))
        self.label_in.setText(_translate("MainWindow", "请导入代码并选择作战次数"))
        self.label_filetip.setText(_translate("MainWindow", "    请完成代码导入!"))
        self.label_numtip.setText(_translate("MainWindow", "    请选择作战次数!"))
        self.label_3.setText(_translate("MainWindow", "作战次数"))
        self.comboBox.setItemText(0, _translate("MainWindow", "未选择"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1000"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2000"))
        self.comboBox.setItemText(3, _translate("MainWindow", "3000"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4000"))
        self.comboBox.setItemText(5, _translate("MainWindow", "5000"))
        self.label_2.setText(_translate("MainWindow", "Loading..."))
        self.group1_nameout.setText(_translate("MainWindow", "组名"))
        self.group2_nameout.setText(_translate("MainWindow", "组名"))
        self.pushButton_detail.setText(_translate("MainWindow", "查看作战结果详情"))
        self.label_8.setText(_translate("MainWindow", "平均分数："))
        self.label_9.setText(_translate("MainWindow", "平均采蜜量："))
import res_rc
